services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    env_file: .env

  api:
    image: node
    command: sh -c "npm run dev"
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env

volumes:
  postgres_data:
