services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: .env

  api:
    image: node
    command: sh -c "npm start"
    ports:
      - '${PORT}:${PORT}'
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env

volumes:
  postgres_data:
